GET http://127.0.0.1:4000
###
POST http://127.0.0.1:4000
Content-Type: application/json

{
    "nama": "dika",
    "prodi": "teknik komputer"
}
###
DELETE http://127.0.0.1:4000/dika

###
PUT http://127.0.0.1:4000
Content-Type: application/json

{
    "nama": "dikagod",
    "prodi": "teknik komputer"
}